institutions:
  - name: "M&T Bank"
    workday_url: "https://mtb.wd5.myworkdayjobs.com/wday/cxs/mtb/MTB/jobs"
    search_text: "sql"
    locations:
      - "Buffalo, NY"
      - "Remote, USA"

  - name: "Bank of America"
    workday_url: "https://ghr.wd1.myworkdayjobs.com/wday/cxs/ghr/Lateral-US/jobs"
    search_text: "sql"

  - name: "Citi"
    workday_url: "https://citi.wd5.myworkdayjobs.com/wday/cxs/citi/2/jobs"
    search_text: "sql"
    locations:
      - "Getzville New York United States"
